AllCops:
  Exclude:
    - 'db/**/*'
    - "vendor/**/*"
    - "spec/support/**/*"
    - "**/*.gemspec"
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.5.1

Layout/EndAlignment:
  Enabled: false

Bundler/OrderedGems:
  Enabled: False

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Layout/AlignArray:
  Enabled: false

Layout/AlignHash:
  EnforcedLastArgumentHashStyle: always_ignore

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/AsciiComments:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/ClosingParenthesisIndentation:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/IndentationWidth:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/NumericPredicate:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 180

Metrics/ClassLength:
  Max: 300

Metrics/MethodLength:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
