version: '3'
services:
  db:
    image: postgres:10.7-alpine
    ports:
      - "5432:5432"
  cache:
    image: redis:5.0.5-alpine
    ports:
      - "6379:6379"
  app:
    build: .
    command: hanami server
    environment:
      HANAMI_ENV: development
      DATABASE_URL: postgres://postgres@db/ennigaldi_development
      REDIS_URL: redis://cache:6379/1
    ports:
      - "5000:5000"
    volumes:
      - $PWD:/app
    depends_on:
      - db
      - cache
